### ISSUE TITLE
fix: headers not included in request on web platform

### ISSUE THREAD

**Issue by wkok** [felangel/web_socket_client#48]
**Description**

When specifying headers in the connect request, they are not included in the server request when the platform is web. 

(It works on linux)

**Steps To Reproduce**

v0.1.1

```dart
import 'package:web_socket_client/web_socket_client.dart';

WebSocket connect(url) {
  return WebSocket(url, headers: {"test": "header"});
}
```

**Expected Behavior**

Headers to be included in the network request.

**Screenshots**

It works on linux:

![Screenshot from 2024-04-27 07-12-56](https://github.com/felangel/web_socket_client/assets/5214136/62144399-b25f-427e-a578-9b0810a182b9)

but not on web (chrome):

![Screenshot from 2024-04-27 07-25-31](https://github.com/felangel/web_socket_client/assets/5214136/e1fa7f3e-b79a-45cd-9011-2354b3e2c0af)

**Comment by felangel** [comment]
Hi @wkok 👋 
Thanks for opening an issue!

This is working as intended because afaik it's not possible to set headers as part of the [WebSocket MDN Specification](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/WebSocket).

Also see https://stackoverflow.com/questions/4361173/http-headers-in-websockets-client-api.

Hope that helps 👍

**Comment by wkok** [comment]
Thanks for the links, I've opted for going the protocols route and sending the data in the `Sec-WebSocket-Protocol` headers as [suggested here](https://stackoverflow.com/a/77060459)
